export const filmImages = [
	// Asia
	{ source: '/photography/Asia/bella-elephant.webp', category: 'Asia' },
	{ source: '/photography/Asia/bella-fancipan.webp', category: 'Asia' },
	{ source: '/photography/Asia/joe-lila.webp', category: 'Asia' },
	{ source: '/photography/Asia/philipines.webp', category: 'Asia' },
	{ source: '/photography/Asia/japan-food.webp', category: 'Asia' },
	{ source: '/photography/Asia/bella-fuji.webp', category: 'Asia' },
	{ source: '/photography/Asia/water-buffalo.webp', category: 'Asia' },
	{ source: '/photography/Asia/bella-thailand.webp', category: 'Asia' },
	{ source: '/photography/Asia/joe-fuji.webp', category: 'Asia' },
	{ source: '/photography/Asia/thailand-skyline.webp', category: 'Asia' },
	{ source: '/photography/Asia/sapa-hike.webp', category: 'Asia' },
	{ source: '/photography/Asia/shibuya-crossing.webp', category: 'Asia' },
	{ source: '/photography/Asia/lila.webp', category: 'Asia' },
	{ source: '/photography/Asia/bella-ghibli.webp', category: 'Asia' },
	{ source: '/photography/Asia/ghibli-museum.webp', category: 'Asia' },
	// 2022
	{ source: '/photography/2022/joes-tuff.webp', category: '2022' },
	{ source: '/photography/2022/stepback-j.webp', category: '2022' },
	{ source: '/photography/2022/joe-candid.webp', category: '2022' },
	{ source: '/photography/2022/reba-leslie.webp', category: '2022' },
	{ source: '/photography/2022/jea-dog.webp', category: '2022' },
	{ source: '/photography/2022/reba.webp', category: '2022' },
	{ source: '/photography/2022/camerastore.webp', category: '2022' },
	{ source: '/photography/2022/summercamp.webp', category: '2022' },
	{ source: '/photography/2022/houseboat.webp', category: '2022' },
	{ source: '/photography/2022/vlad-party.webp', category: '2022' },
	{ source: '/photography/2022/brown.webp', category: '2022' },
	{ source: '/photography/2022/grossy.webp', category: '2022' },
	{ source: '/photography/2022/birthday.webp', category: '2022' },
	{ source: '/photography/2022/mother.webp', category: '2022' },
	{ source: '/photography/2022/concert.webp', category: '2022' },
	// 2024
	{ source: '/photography/2024/kbbq.webp', category: '2024' },
	{ source: '/photography/2024/whitelake.webp', category: '2024' },
	{ source: '/photography/2024/griffin.webp', category: '2024' },
	{ source: '/photography/2024/painted-ladies.webp', category: '2024' },
	{ source: '/photography/2024/hackathon-utd.webp', category: '2024' },
	{ source: '/photography/2024/yates.webp', category: '2024' },
	{ source: '/photography/2024/cherry-republic.webp', category: '2024' },
	{ source: '/photography/2024/cheddarbox-utd.webp', category: '2024' },
	{ source: '/photography/2024/cheers.webp', category: '2024' },
	{ source: '/photography/2024/mira-DIA.webp', category: '2024' },
	{ source: '/photography/2024/mira.webp', category: '2024' }
];
